### PR TITLE
Fix emojis and Legit's autism

### PR DESCRIPTION
**Pull request by Villagers654**
Fixed some emojis that relied on 4b (which is closing) by using identical/similar ones in endzone, and I made the bot a million times better by reverting the worst commit in its history

### CODE REVIEW

**Review by Legit4K — CHANGES_REQUESTED** [review]
I agree with replacing the emojis but removing the emoji thief prevention probably not gonna work out for u

**Comment by Villagers654** [comment]
Comprimise

**Comment by Villagers654** [comment]
wait actually 4b is dead I can remove it

**Comment by Villagers654** [comment]
much better

**Review by Legit4K — APPROVED** [review]
_now it's ready for merge :troll:_

**Pull request merged**
